name: Generate preview link

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
    build_and_deploy_preview_link:
        runs-on: Ubuntu-latest
        permissions:
          checks: write
          pull-requests: write
        steps:
          - name: Build
            run: |
                  mkdir test
                  cd test

          - name: Setup Noode
            uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
            with:
                  node-version: 18.x
