name: Generate preview link

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
    build_and_deploy_preview_link:
        runs-on: Ubuntu-latest
        permissions:
          checks: write
          pull-requests: write
        steps:
          - uses: actions/checkout@v2
            with:
              ref: ${{ github.event.pull_request.head.sha }}
          - name: Build
            run: |
                  cat README.md
                  mkdir test
                  cd test

          - name: Setup Node
            uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8
            with:
                  node-version: 18.x
